
export enum StateEnum {
    SHOULD_INIT_SHUFFLING,
    FIRST_SHUFFLING_WAITING_OTHERS,
    SHOULD_INIT_SECOND_SHUFFLING_ROUND,
    SECOND_SHUFFLING_WAITING_OTHERS,
    DEAL_CARDS,
    WAITING_MY_CARDS,
    START_GAME,
}
